name: Publish docs to Wiki

on:
  workflow_dispatch:
  push:
    paths:
      - "docs/**"
      - .github/workflows/wiki.yml
    branches:
      - master

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
      - name: Copy Readme
        run: cp ./README.md ./docs/Home.md
      - name: Sidebar Installer
        run: npm install -g github-wiki-sidebar
      - name: Sidebar Installer
        run: (cd docs && github-wiki-sidebar --silent)
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs
